CRF_GearScriptConfig {
 m_FactionName "Fisherman"
 m_FactionIcon "{0BFF16B743E646E5}Assets/Structures/BuildingsParts/Mural/Data/Murals_fisherman_b_BCR.edds"
 m_FactionIdentity "{93C4AAA0496F0B42}Configs/Identities/North America/CRF_CharacterIdentity_American.conf"
 m_DefaultClothing {
  CRF_Clothing "{696820BBCC10E243}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{C28000066BF1E1C9}Prefabs/Characters/HeadGear/Hat_Beanie/variants/Hat_beanie_MEC.et"
    "{5A1FBEA5592CEAF1}Prefabs/Characters/HeadGear/Hat_Beanie/Hat_beanie_MEC_tan.et"
   }
  }
  CRF_Clothing "{696820BBCC10E24B}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{7F1451790F3D75BD}Prefabs/Characters/Uniforms/Jacket_Raincoat_01/Jacket_Raincoat_01_green.et"
    "{50F8B1F928F93ABD}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Shirt_Turtleneck_01_beige.et"
    "{B0F4EAC29E9058EA}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Shirt_Turtleneck_01_grey.et"
    "{6A3F994EFFE22995}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Shirt_Turtleneck_01_DarkBlue.et"
    "{690819A92A3A8D14}Prefabs/Characters/Uniforms/Jacket_Raincoat_01/Jacket_Raincoat_01_orange.et"
    "{FD39B0B833BB927E}Prefabs/Characters/Uniforms/Jacket_Raincoat_01/Jacket_Raincoat_01_yellow.et"
   }
  }
  CRF_Clothing "{696820BBCC10E248}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{0B1F0174869E0351}Prefabs/Characters/Uniforms/Pants_Fisherman_01/Pants_Fisherman_01_green.et"
    "{5B29F970DC4022D5}Prefabs/Characters/Uniforms/Pants_Fisherman_01/Pants_Fisherman_01_orange.et"
    "{CF185061C5C13DBF}Prefabs/Characters/Uniforms/Pants_Fisherman_01/Pants_Fisherman_01_yellow.et"
   }
  }
  CRF_Clothing "{696820BBCC10E249}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
   }
  }
 }
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{696820BBCC10E256}" {
   m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{696820BBCC10E257}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{696820BBCC10E255}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{696820BBCC10E252}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{696820BBCC10E253}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 1
  }
 }
 m_MedicMedicalItems {
  CRF_Inventory_Item "{696820BBCC1343B9}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 10
  }
  CRF_Inventory_Item "{696820BBCC1343BA}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 3
  }
  CRF_Inventory_Item "{696820BBCC1343BB}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{696820BBCC1343B4}" {
   m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{696820BBCC134234}" {
   m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
   m_iItemCount 5
  }
  CRF_Inventory_Item "{696820BBCC134235}" {
   m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
   m_iItemCount 1
  }
 }
}