CRF_GearScriptConfig {
 m_FactionName "Canadian Coastguard"
 m_FactionIcon "{8C37AA80F865D794}Assets/Characters/Patches/data/patch_Canada_flag_embroidered_BCR.edds"
 m_FactionIdentity "{93C4AAA0496F0B42}Configs/Identities/North America/CRF_CharacterIdentity_American.conf"
 m_DefaultClothing {
  CRF_Clothing "{696820BC9D8610EB}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{98841059F2166DAC}Clothing/Rus_Police Man/Hat/Police Hat.et"
   }
  }
  CRF_Clothing "{696820BC9D8610FC}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{05F042A3599FEED7}Clothing/Rus_Police Man/Jacket/Police jacket.et"
   }
  }
  CRF_Clothing "{696820BC9D8610FD}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{4AB95C821AFEAD58}Clothing/Rus_Police Man/Pants/Police Pants.et"
   }
  }
  CRF_Clothing "{696820BC9D8610FE}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
   }
  }
 }
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{696820BC9D8610FF}" {
   m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{696820BC9D8610F8}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{696820BC9D8610F9}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{696820BC9D8610FA}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{696820BC9D8610FB}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 1
  }
 }
 m_MedicMedicalItems {
  CRF_Inventory_Item "{696820BC9D8610F4}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 10
  }
  CRF_Inventory_Item "{696820BC9D8610F5}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 3
  }
  CRF_Inventory_Item "{696820BC9D8610F6}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{696820BC9D8610F7}" {
   m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{696820BC9D861309}" {
   m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
   m_iItemCount 5
  }
  CRF_Inventory_Item "{696820BC9D86130A}" {
   m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
   m_iItemCount 1
  }
 }
}